# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='graduate_school',
            name='location',
            field=models.CharField(help_text='ㅇㅇ동 ㅇㅇㅇ호', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graduate_school',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graduate_school',
            name='professor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graduate_school',
            name='telephone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='graduate_school',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='연구실 이름'),
        ),
        migrations.AlterField(
            model_name='graduate_school',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
